# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "648a1b08119795c32a05151badb6d834"
name = "Product Assembly Services"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_cart_transforms"

# Assembly service cost on the product
[product.metafields.assembly-service.cost]
name = "Assembly Service Cost"
type = "json"
access.admin = "merchant_read_write"

# Assembly service variant ID on cart transform
[cart_transform.metafields.optional-add-ons.function-configuration]
name = "Assembly Service Variant ID"
type = "single_line_text_field"
access.admin = "merchant_read_write"


[auth]
redirect_urls = [ "https://example.com/api/auth" ]
