api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cart-add-on-expander"
type = "function"
uid = "88aea7dd-d410-9268-5990-ccf05e929fcdd0316450"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
